### ISSUE TITLE
Line wrapping doesn't work

### ISSUE THREAD

**Issue by nevillepark** [maze-n/eddit#1]
Hi! Just found this application, it was exactly what I was looking for. However, based on the screenshots, I expected long lines of text to wrap. They don't.

![Screenshot from 2021-08-20 19 04 38](https://user-images.githubusercontent.com/16054979/130301312-ca206a81-dd6e-487c-b4d0-cbb28280f5c9.png)

**Comment by maze-n** [comment]
Hey,

Thanks for checking out this little project :). As of now I'm adding radio buttons to choose one line wrap ping mode and sorry to say that it may take some time as I'm currently busy for some time.

**Comment by nevillepark** [comment]
No worries, I know you're just one person and have other stuff to work on! Thanks for letting me know.

**Comment by maze-n** [comment]
Hey, just added the widgets and functions to set text wrapping and available in the latest master branch, so closing this issue now. Please let me know if there is any problems or suggestion.
